build fixes for when openssl engine is disabled
linux-integrity/ima-evm-utils pull request #6
Opened 2024-07-04 13:19 UTC by nullr0ute

Add and fix checks for building with the option for disabling the openssl engine option. In cases now
it's possible that engine.h now actually may not be present as distros may split out the engine support into other devel packages. This fixes the builds.

2024-07-05 14:31 UTC, stefanberger requested changes

2024-07-05 14:31 UTC, stefanberger commented on src/imaevm.h
> +#if CONFIG_IMA_EVM_ENGINE
You cannot do this in a public header file that other apps may #include. They don't know about this CONFG_IMA_EVM_ENGINE.

Here is what seems to be necessary now with rawhide:
`+#if !defined(OPENSSL_NO_ENGINE) && !defined(OPENSSL_NO_DYNAMIC_ENGINE) && !defined(OPENSSL_NO_STATIC_ENGINE)`

2024-07-05 14:33 UTC, stefanberger commented
I also found that this here was necessary for rawhide:
```
diff --git a/configure.ac b/configure.ac
index c4c7f68..23ea40c 100644
--- a/configure.ac
+++ b/configure.ac
@@ -59,6 +59,7 @@ AC_ARG_ENABLE(sigv1,
 AC_ARG_ENABLE(engine,
              [AS_HELP_STRING([--disable-engine], [build ima-evm-utils without OpenSSL engine support])],,[enable_engine=yes])
        AC_CHECK_LIB([crypto], [ENGINE_init],, [enable_engine=no])
+       AC_CHECK_HEADERS(openssl/engine.h, , [enable_engine=no])
        AM_CONDITIONAL([CONFIG_IMA_EVM_ENGINE], [test "x$enable_engine" = "xyes"])

 AC_ARG_ENABLE(provider,
```

2024-08-08 23:57 UTC, mimizohar commented
Closing pull request based on the discussion above.   A more complete solution was posted.

2024-08-08 23:57 UTC, closed without merging